### ISSUE TITLE
Styled Component TypeError

### ISSUE THREAD

**Issue by bohaesoju** [landvibe/book-react#1]
챕터 1 6-css-test 에서

app.js 에서 box4-1.js 로 바꾸고 실행 시키면

TypeError: BoxCommon.extend is not a function 가 납니다 !

Mac 환경인 제 PC 만 이상인지 모르겠네요

노드는 10점대를 사용중입니다.

**Comment by landvibe** [comment]
제보 감사합니다.
styled-components 버전이 올라가면서 API가 변경됐네요
https://github.com/landvibe/book-react/blob/master/corrections.md
