### ISSUE TITLE
351p CleanWebpackPlugin issue

### ISSUE THREAD

**Issue by YongHoonJJo** [landvibe/book-react#10]
`const CleanWebpackPlugin = require('clean-webpack-plugin')`

모듈을 위와 같이 불러온 다음 웹팩을 실행시키면,
CleanWebpackPlugin is not a constructor 이란 메세지가 뜨면서 실행이 되지 않습니다.

`const { CleanWebpackPlugin } = require('clean-webpack-plugin')` 
이와 같이 불러와서 해결하였습니다.

Reference : https://github.com/johnagan/clean-webpack-plugin

**Comment by landvibe** [comment]
@YongHoonJJo 제보 감사합니다!
문서에 반영했습니다.
https://github.com/landvibe/book-react/blob/master/corrections.md#%EC%9C%84%EC%B9%98-p351-%EC%BD%94%EB%93%9C-7-65
