### ISSUE TITLE
1-44, 1-47 오탈자 문의

### ISSUE THREAD

**Issue by 8c6t** [landvibe/book-react#12]
1. 코드 1-44의 `onChangPage` 함수명이 문맥상 `onChangePage` 인것 같습니다.
2. 코드 1-47의 Link 컴포넌트 중 파란 방의 to 속성값이 `/bludRoom`이 아닌 `/blueRoom` 인것 같습니다.

**Comment by landvibe** [comment]
@8c6t 제보 감사합니다!
문서에 반영했습니다.
https://github.com/landvibe/book-react/blob/master/corrections.md#%EC%9C%84%EC%B9%98-p45-%EC%BD%94%EB%93%9C-1-44
https://github.com/landvibe/book-react/blob/master/corrections.md#%EC%9C%84%EC%B9%98-p48-%EC%BD%94%EB%93%9C-1-47
