### ISSUE TITLE
3장 코드 3-38, 3-39 오탈자 확인 부탁드립니다.

### ISSUE THREAD

**Issue by skid901** [landvibe/book-react#13]
안녕하세요.
좋은 책 써주셔서 덕분에 잘 읽고 있습니다.
책 예제에서 오탈자를 발견한 것 같아 제보드립니다.

'3장 중요하지만 헷갈리는 리액트 개념 이해하기'에서
'3.3 생명 주기 메서드' 부분의 '코드 3-38 key 속성값을 이용한 코드'의
(1) 번
`return <PriceInput key={product.id} value={product.price} />;`
->
`return <PriceInput key={product.id} price={product.price} />;`
로 수정되어야 하는거 같은데 확인 부탁드립니다.

또한, '코드 3-39 상탯값을 부모 컴포넌트에서 관리하는 코드'의
13번째 줄
`return <PriceInput onChange={this.onChangePrice} value={product.price} />;`
->
`return <PriceInput onChange={this.onChangePrice} price={product.price} />;`
도 확인 부탁드립니다.

감사합니다.

**Comment by landvibe** [comment]
@skid901 제보 감사합니다!
문서에 반영했습니다^^
https://github.com/landvibe/book-react/blob/master/corrections.md#%EC%9C%84%EC%B9%98-p133-%EC%BD%94%EB%93%9C-3-38
https://github.com/landvibe/book-react/blob/master/corrections.md#%EC%9C%84%EC%B9%98-p134-%EC%BD%94%EB%93%9C-3-39
