### ISSUE TITLE
p.273 값에 의한 호출과 참조에 의한 호출, 잘못된 내용이 아닌가 싶은데

### ISSUE THREAD

**Issue by ad7549** [landvibe/book-react#15]
해당 지문에서 filter를 사용하면 의도한 대로 되지 않는다고 해서, filter가 안 되면 splice도 안 돼야 하는 게 맞지 않냐는 생각에 실제 테스트를 해봤습니다.

// const index = state[name].findIndex(item => item.id === action.item.id);
// state[name].splice(index, 1);
state[name] = state[name].filter(item => item.id !== action.item.id);

위와 같이 코드 6-34에서 원래 REMOVE 부분에 있던 소스를 주석 처리하고, filter로 바꿨는데 잘 작동합니다.

확인 부탁드립니다.

**Comment by landvibe** [comment]
책을 쓰는 과정에서 코드가 수정되면서 문맥상 어울리지 않는 설명이 되었네요.
처음에 예제 코드는 아래와 같은 구조로 작성했던 것 같습니다.
```ts
const reducer = createReducer([], {
  // ...
  [REMOVE]: (state, action) => {
    const index = state.findIndex(item => item.id === action.item.id);
    state.splice(index, 1);
  },
  // ...
});
```

위 코드에서는 아래처럼 작성하면 원하는대로 동작하지 않구요.
`state = state.filter(item => item.id !== action.item.id);`

그러나 이후 `state[name]` 형식으로 코드를 변경하면서 문맥상 어울리지 않는 설명이 되었네요.
좋은 지적 감사합니다^^
2쇄에서는 해당 설명을 삭제하는 게 좋겠네요.

**Comment by landvibe** [comment]
@ad7549 해당 내용 문서에 작성했습니다.
https://github.com/landvibe/book-react/blob/master/corrections.md#%EC%9C%84%EC%B9%98-p273-%EA%B8%80%EC%83%81%EC%9E%90
