### ISSUE TITLE
p111 코드 3-7 props.title 부분

### ISSUE THREAD

**Issue by clnarisu** [landvibe/book-react#17]
p. 111의 코드 3-7에서 클래스형 컴포넌트 부분에서
{props.title} 을 {this.props.title}로 변경해야 할 것 같습니다.

**Comment by landvibe** [comment]
@clnarisu 제보 감사합니다!
문서에 반영했습니다.
https://github.com/landvibe/book-react/blob/master/corrections.md#%EC%9C%84%EC%B9%98-p111-%EC%BD%94%EB%93%9C-3-7
