### ISSUE TITLE
212p 코드 4-55 메모이제이션 사용 예

### ISSUE THREAD

**Issue by almond-bongbong** [landvibe/book-react#2]
안녕하세요, 212p 코드 4-55 메모이제이션 사용 예제에서 output1, output2, output3을 얻기위해 호출되는 함수가 sort가 아닌 sort2가 되어야 하는게 아닌지 궁금합니다 🤔 

별개로 책의 내용이 풍성해서 감사합니다! 😄

**Comment by landvibe** [comment]
제보 감사합니다!
문서 업데이트 했습니다^^
https://github.com/landvibe/book-react/blob/master/corrections.md#%EC%9C%84%EC%B9%98-p212-%EC%BD%94%EB%93%9C-4-55
