### ISSUE TITLE
p 143 - 오탈자 문의

### ISSUE THREAD

**Issue by ByeongGi** [landvibe/book-react#20]
안녕하세요. 이재승님
책을 읽던 중에 내용상 안 맞는 것 같아서 제보 드립니다.
 
p 143 내용중 일부

AS IS
>  단지, componentDidUpdate 메서드가 첫 렌더링 후에 호출되지 않는다는 이후로 코드가 복잡해진다.

TO BE
>  단지, componentDidMount 메서드가 첫 렌더링 후에 호출되지 않는다는 이후로 코드가 복잡해진다.  

내용상 componentDidUpdate 보다는 componentDidMount 맞을 것 같습니다.

**Comment by landvibe** [comment]
@ByeongGi 제보 감사합니다!
오탈자 문서에 반영했습니다.
https://github.com/landvibe/book-react/blob/master/corrections.md#%EC%9C%84%EC%B9%98-p143
