### ISSUE TITLE
개정판 424p ~ 425p의 내용에 오탈자가 있는 것 같습니다...

### ISSUE THREAD

**Issue by imssshrek** [landvibe/book-react#22]
안녕하세요. 좋은 책 써 주셔서 감사합니다. 많은 도움이 되고 있습니다.
공부를 하다가 작동이 잘 안되는 부분이 있어서 글 올립니다.
먼저 424p의 [코드 8-29]의 production 환경에서의 `prerenderCache`를 생성하는 부분에서,
```javascript
if (!dev) {
  for (const info of prerenderList) {
    const { name, path } = info;
    const html = fs.readFileSync(`./out/${name}.html`, "utf8");
    prerenderCache[path] = html;
  }
}
```
라고 작성되어 있는데요.
브라우저에서 책에서와 같이 `localhost:3000/page2-hello` 또는 `localhost:3000/page2-world`로 요청하면 페이지를 찾을 수 없게 됩니다.
`renderAndCache`함수에서 `cacheKey` 변수에는 `/page2-hello` 또는 `/page2-world`가 담기게 되고, `prerenderCache`객체의 key에는 각 페이지에 대한 주소와 쿼리가 담겨 있어 정상적으로 작동하지 않습니다.
그래서 위의 코드를 아래와 같이 수정하였더니 정상적으로 작동되었습니다.
```javascript
if (!dev) {
  for (const info of prerenderList) {
    const { name } = info;
    const html = fs.readFileSync(`./out/${name}.html`, "utf8");
    prerenderCache[`/${name}`] = html; // path를 `/${name}`으로 변경
  }
}
```
제가 아직 책을 100% 이해하지 못해 이것이 필자께서 의도하신 결과인지는 잘 모르겠습니다.
혹시 제가 잘못 이해한 것이 있다면 지적해주시면 좋겠습니다!

그리고 424p의

> 브라우저에서 http://localhost:3000/page2-hello로 접속해 보면 ... 해결할 수 있다.

단락의 url에 html 확장자가 빠진 듯 하고,
425p의 [8.4.6 styled-components 사용하기] 직전의 단락과 내용이 중복되어 편집에 오류가 있는 것 같아 보입니다.

확인하시고 정정해주시면 감사하겠습니다!

**Comment by landvibe** [comment]
안녕하세요
답변을 늦게 달아서 죄송합니다.
말씀해주신 내용은 아래 링크에 반영했습니다.
https://github.com/landvibe/book-react/blob/revision2/corrections.md

링크에서 수정된 설명으로 prerenderCache 부분은 별도 수정없이 내용 전달이 될 것 같습니다
`/page2-hello` 로 요청하는 것이 아니고 `/page2?text=hello` 로 요청하는 방식을 의도했습니다

오탈자 제보 감사합니다~!
