### ISSUE TITLE
p24 __tset__ 스펠링 오탈자가 있습니다.

### ISSUE THREAD

**Issue by leekeunhwan** [landvibe/book-react#3]
" _ _ tset _ _ " 폴더 밑에 있는 모든 자바스크립트 파일이라고 되어있는데
" _ _ tests _ _ " 로 정정되어야 할 것 같습니다.

책 너무 내용좋습니다.. 진짜 너무 공부가 잘되는거같아요! 감사합니다!!:)
붙이면 볼드처리되어 일부러 언더스코어는 띄었습니다.

**Comment by landvibe** [comment]
오탈자 찾아주셔서 감사합니다😊
문서에 반영했습니다.
https://github.com/landvibe/book-react/blob/master/corrections.md#%EC%9C%84%EC%B9%98-p24
