### ISSUE TITLE
p65 함수를 이용한 기본값 코드 결과값이 다릅니다.

### ISSUE THREAD

**Issue by leekeunhwan** [landvibe/book-react#4]
```
function getDefaultAge() {
      console.log('Hello');
      return 0;
}

const obj = { age:21, grade: 'A' };
const  {age = getDefaultAge(), grade } = obj;
console.log(age); // 0
```

요렇게 코드가 나와있는데,
age의 속성값이 undefined가 있으므로, 기본값이 사용되지 않았으므로
hello도 호출되지 않았기에 값도 0이 아닌 21이 되어야할 것 같습니다.

**Comment by landvibe** [comment]
오류 잡아주셔서 감사합니다!
문서에 반영했습니다.
https://github.com/landvibe/book-react/blob/master/corrections.md#%EC%9C%84%EC%B9%98-p65-%EC%BD%94%EB%93%9C-2-39
