### ISSUE TITLE
p67 코드 2-45 코드 에러가 있습니다.

### ISSUE THREAD

**Issue by leekeunhwan** [landvibe/book-react#5]
```
const obj = {};
const arr = [];

({ foo: obj.prop, bar: arr[0] }) = {foo:123, bar:true};
console.log(obj); // {prop:123}
console.log(arr); // [true]
```

해당 코드를 실행시켜보면 에러가 납니다.
(Uncaught SyntaxError: Invalid destructuring assignment target)
아래처럼 코드를 수정하여 에러를 대응하면 콘솔로그의 기대값이 올바르게 출력됩니다.
수정이 괄호의 수정이 필요할 것 같습니다..!!:)
정말 많이 배우고 있습니다..!
감사합니다!!:)

```
const obj = {};
const arr = [];

({ foo: obj.prop, bar: arr[0] } = {foo:123, bar:true});
console.log(obj);
console.log(arr);

```

**Comment by landvibe** [comment]
오류 위치와 해결책까지 알려주셔서 너무 감사합니다^^
도움이 되신다니 고생해서 책을 쓴 보람이 있네요🙂
문서 업데이트 했습니다.
https://github.com/landvibe/book-react/blob/master/corrections.md#%EC%9C%84%EC%B9%98-p67-%EC%BD%94%EB%93%9C-2-45

**Comment by Fron2** [comment]
안녕하세요. 최근, 이 책을 사서 읽고 있는 독자입니다. 이 코드가 동작하지 않는 것 때문에 찾아보다가, 수정된 코드로는 작동하는 것을 확인했습니다.

그런데, 괄호를 지우고 시도해봐도 코드가 작동하지 않던데, 이러한 문법(괄호로 묶는)은 어떤 키워드로 검색하면, 더 자세한 정보를 볼 수 있을지 궁금합니다.

메일로 여쭙고 싶었는데, 메일을 찾을 수가 없어서, 여기에 남깁니다.
좋은 하루 되세요.

**Comment by leekeunhwan** [comment]
@Fron2 

`구조분해할당(Destructuring assignment)`에 대해서 알아보시면 
정보를 아실 수 있으실거에요!!:)

동작되는 코드인 ({ foo: obj.prop, bar: arr[0] } = {foo:123, bar:true});은
obj = {prop: 123}, arr = [true]와 같습니다.

**Comment by Fron2** [comment]
@leekeunhwan 
감사합니다. 덕분에 잘 해결했습니다 :)
