### ISSUE TITLE
6.5 오탈자 문의

### ISSUE THREAD

**Issue by YongHoonJJo** [landvibe/book-react#6]
291p 코드 6-58 에서 `getAgeLimit` 과 `getShowLimit` 에 export 가 빠진 것 같습니다. ㅜ

**Comment by landvibe** [comment]
@YongHoonJJo 제보 감사합니다🙂
문서 업데이트 했습니다.
https://github.com/landvibe/book-react/blob/master/corrections.md#%EC%9C%84%EC%B9%98-p291-%EC%BD%94%EB%93%9C-6-58
