### ISSUE TITLE
오탈자 문의

### ISSUE THREAD

**Issue by ad7549** [landvibe/book-react#7]
5p. 코드 1-1 simple1.html 5번째 줄
<script src="react.development.js"/></script>가 아니라
<script src="react.development.js"></script>인 것 같습니다.

**Comment by landvibe** [comment]
@ad7549 제보 감사합니다!
문서 업데이트 했습니다.
https://github.com/landvibe/book-react/blob/master/corrections.md#%EC%9C%84%EC%B9%98-p5-%EC%BD%94%EB%93%9C-1-1
