### ISSUE TITLE
3장 p.109 코드 3-4 오탈자 문의

### ISSUE THREAD

**Issue by dowookims** [landvibe/book-react#8]
```js
<button style={{ backgroundColor: this.color }} .... >
  좋아요
</button>
```
라고 책에 적혀져 있는데 `backgroundColor`에서 `state`에 있는 `color` 값에 접근하는 로직이라 

`this.color` 를 `this.state.color`로 해야 색상이 바뀌네요.

**Comment by landvibe** [comment]
제보 감사합니다!
문서에 반영했습니다.
https://github.com/landvibe/book-react/blob/master/corrections.md#%EC%9C%84%EC%B9%98-p109-%EC%BD%94%EB%93%9C-3-4
