### ISSUE TITLE
3장 코드 3-20 오타 문의

### ISSUE THREAD

**Issue by dowookims** [landvibe/book-react#9]
```js
const element = <a href="http://google.com">click here</a>;
elements.type ='b'; // 에러발생
```
두번째 문장인  `elements.type` 에서 오타인거 같습니다. 아마 element로 바꿔야 하지 않을까 싶습니다.

**Comment by landvibe** [comment]
@dowookims 제보 감사합니다!
문서에 반영했습니다.
https://github.com/landvibe/book-react/blob/master/corrections.md#%EC%9C%84%EC%B9%98-p118-%EC%BD%94%EB%93%9C-3-20
